### ISSUE TITLE
defining a different port doesn't work

### ISSUE THREAD

**Issue by halpz** [cooperspencer/paper-docker#1]
when I change the line -p 25565:25565 to a different port, it always starts the server on port 25565

```
version: '3.3'
services:
    papermc:
        container_name: papermc
        environment:
            - MEMORYSIZE=1G
        volumes:
            - /srv/dev-disk-by-uuid-EEFE3DB9FE3D7B43/papermc:/data:rw
        ports:
            - 3000:3000
        image: buddyspencer/papermc:latest
```
